'\"
.\" $Format: ".TH RGLCLOCK 1 \"$Date$\" \"$Project$ $ProjectVersion$\"" $
.TH RGLCLOCK 1 "Fri, 31 Jul 1998 11:24:28 +0900" "rglclock 0.48"
.SH NAME
rglclock \- rotating 3D clock
.SH SYNOPSIS
.B rglclock
.SH DESCRIPTION
This manual page is a preliminary one, and possibly does not
document all of
.BR rglclock.

.B rglclock
displays the time in a rotating 3D clock.
The rotation direction and speed can be changed by a mouse drag.
.SH OPTIONS
.B rglclock
accepts all standard GTK+ options.
